---
version: 1.3.9
slug: assist_microphone_custom
name: Assist Microphone Custom
description: Use Assist with local microphone
url: https://github.com/pikeman20/hassio-addons/blob/master/assist_microphone
hassio_api: true
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
map:
  - share:ro
options:
  awake_wav: "/usr/src/sounds/awake.wav"
  done_wav: "/usr/src/sounds/done.wav"
  timer_finished_wav: "/usr/src/sounds/timer_finished.wav"
  timer_repeat_count: 3
  timer_repeat_delay: 0.75
  sound_enabled: true
  noise_suppression: 0
  auto_gain: 0
  mic_volume_multiplier: 1.0
  sound_volume_multiplier: 1.0
  debug_logging: false
  mic_command: "arecord -r 16000 -c 1 -f S16_LE -t raw"  # Microphone command (default: arecord -r 16000 -c 1 -f S16_LE -t raw)
  snd_command: "aplay -r 16000 -c 1 -f S16_LE -t raw"    # Speaker command (default: aplay -r 16000 -c 1 -f S16_LE -t raw)
  snd_command_rate: 16000                                # Speaker sample rate (default: 16000)
  use_tcp_pulse: false                                   # Enable TCP Pulse server for audio/mic
  tcp_pulse_host: ""                                     # Host of TCP Pulse server
  tcp_pulse_port: 4713                                   # Port of TCP Pulse server (default: 4713)
  sink_name: "remote_speaker_win"                        # PulseAudio sink name
  source_name: "remote_mic_win"                          # PulseAudio source name
schema:
  awake_wav: str
  done_wav: str
  timer_finished_wav: str
  timer_repeat_count: int
  timer_repeat_delay: float
  sound_enabled: bool
  noise_suppression: int
  auto_gain: int
  mic_volume_multiplier: float
  sound_volume_multiplier: float
  debug_logging: bool
  mic_command: str?
  snd_command: str?
  snd_command_rate: int?
  use_tcp_pulse: bool
  tcp_pulse_host: str?
  tcp_pulse_port: int?
  sink_name: str?
  source_name: str?
audio: true
full_access: true
host_network: true
homeassistant: 2023.12.1