# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Real-time Microphone Filter"
  org.opencontainers.image.description: "Real-time microphone filtering for Home Assistant Assist with virtual audio device support"
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"