---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base
  aarch64: ghcr.io/home-assistant/aarch64-base
  armv7: ghcr.io/home-assistant/armv7-base
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
args:
  PROXY_MANAGER_VERSION: 1.1.2
