---
name: Nginx Proxy Manager
version: 1.0.22
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:81]
startup: services
init: false
ingress: true
ingress_port: 8181
ingress_stream: true
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: null
  443/tcp: null
  1443/tcp: 443
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"

image: ghcr.io/pikeman20/addon-nginx-proxy-manager-proxy-manager-{arch}

options:
  debug: false

schema:
  debug: bool