---
name: Real-time Microphone Filter
version: 1.0.0
slug: ha-mic-filter
description: Real-time microphone filtering for Home Assistant Assist with virtual audio device support
url: https://github.com/pikeman20/hassio-addons
arch:
  - aarch64
  - amd64
  - armv7
init: false
audio: true
privileged:
  - SYS_ADMIN
  - SYS_PTRACE
devices:
  - /dev/snd
apparmor: true
map:
  - share:rw
  - config:rw
options:
  input_device: ""
  output_device: ""
  monitoring_device: ""
  virtual_mic_name: HA_Filtered_Mic
  sample_rate: 48000
  channels: 1
  buffer_size_ms: 10
  auto_start: true
  log_level: "info"
  audio_pipeline:
    noise_suppression:
      enabled: true
      method: "rnnoise"
      intensity: 0.8
      suppress_level: -30
    gain:
      enabled: true
      gain_db: 10.5
    equalizer:
      enabled: true
      low_db: 10.0
      mid_db: -20.0
      high_db: 12.5
    expander:
      enabled: true
      ratio: 4.0
      threshold: -55.0
      attack_time: 1.0
      release_time: 75.0
      output_gain: 2.0
    compressor:
      enabled: true
      ratio: 4.0
      threshold: -7.0
      attack_time: 1.0
      release_time: 75.0
      output_gain: 0.0
    limiter:
      enabled: true
      threshold: -0.2
      release_time: 60.0
schema:
  input_device: str?
  output_device: str?
  monitoring_device: str?
  virtual_mic_name: str?
  sample_rate: int?
  channels: int?
  buffer_size_ms: int?
  auto_start: bool?
  log_level: list(debug|info|warning|error)?
  audio_pipeline:
    noise_suppression: "dict(enabled:bool?,method:list(speex|rnnoise)?,intensity:float?,suppress_level:int?)?"
    gain: "dict(enabled:bool?,gain_db:float?)?"
    equalizer: "dict(enabled:bool?,low_db:float?,mid_db:float?,high_db:float?)?"
    expander: "dict(enabled:bool?,ratio:float?,threshold:float?,attack_time:float?,release_time:float?,output_gain:float?)?"
    compressor: "dict(enabled:bool?,ratio:float?,threshold:float?,attack_time:float?,release_time:float?,output_gain:float?)?"
    limiter: "dict(enabled:bool?,threshold:float?,release_time:float?)?"
ports:
  "11400/tcp": null
homeassistant: 2023.11.0