build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  BUMPER_VERSION: 1.0.0
